GRIMs v4.0
Signed-off-by: sul <hb3099@hotmail.com>

diff --git a/expscr/gmp.in b/expscr/gmp.in
--- a/expscr/gmp.in
+++ b/expscr/gmp.in
@@ -19,19 +19,23 @@ fi
 #
 SDATE=2001071400        # Starting forecast date
 ENDHOUR=`expr 24 \* 2`  # Length of model integration in hour
-INCHOUR=$ENDHOUR        # Forecast hour per one execution
 INTSFCX=24              # Time interval to run surface merging
 INTOMLX=24              # Time interval to run ocean mixed layer model
 INTSIG=6                # Time interval to create sigma output file
 INTSFC=6                # Time interval to create surface output file
 INTFLX=6                # Time interval to create surface flux output file
-INTRESTART=$ENDHOUR     # Time interval to restart the model
+INTNCO=6                # Time interavl to create nc output file
 SWHR_GBL=1              # Time interval of shortwave radiation flux (default=6)
-LWHR_GBL=3              # Time interval of longwave  radiation flux
+LWHR_GBL=1              # Time interval of longwave  radiation flux
+INCHOUR=$ENDHOUR        # Forecast hour per one execution
+INTRESTART=24
+#
+NENS_STOCH=1            # Ensemble number for stochastic perturbation
 #
 FCST_RESTART=yes        # Option indicating whether current forecast is first
-DEL_FLUX=yes            # Option deleting flux file after forecst (yes;no)
+DEL_FLUX=no             # Option deleting flux file after forecst (yes;no)
 SIG_GRIB=no             # Option gribing at sigma layer after forecst (yes;no)
+DO_POST=yes             # Option for post processing
 #
 # ------------- below for expert user only -------------------------------------
 #
@@ -50,6 +54,10 @@ export EXECDIR
 # -------------  do not change below  ------------------------------------------
 #
 mkdir -p $EXECDIR 2>/dev/null
+#
+# namelist
+#
+. @RUNSCR_DIR@/namelist $EXECDIR
 #
 INITIAL_SIGMA=@CON_DIR@/sig.anl.$SDATE.ieee
 INITIAL_SFC=@CON_DIR@/sfc.anl.$SDATE.ieee
@@ -84,10 +92,6 @@ FCST_NCPUS=@NCPUS@
 #
 CPSCLD=`grep 'EXPLICIT_CLOUDINESS' @SRCS_DIR@/define.h | awk '{print $1}' | sed 's/\#//g'`
 #
-# set environmental variables
-#
-. @RUNSCR_DIR@/envset
-#
 # cd to run directory
 #
 scrnam=`echo $0 | sed 's?.*/??g'`
@@ -109,14 +113,13 @@ if [ @BARO_TEST@ != 1 ]; then
 		# Restart
 		#
 		h=`@ETC_DIR@/fhour sigit`
-		echo fhour in the sigit file = $h
+        if [ "$h" == "" ]; then
+            echo "error in reading forecast hour of sigit."
+            exit 8
+        else
+            echo fhour in the sigit file = $h
+        fi
 	else
-		#
-		# co2
-		#
-		if [ ! -s co2con ] ; then
-			@RUNSCR_DIR@/co2 || exit 8
-		fi
 		#
 		# mountain
 		#
@@ -128,25 +131,9 @@ if [ @BARO_TEST@ != 1 ]; then
 		#
 		h=00
 		#
-		# Conversion from ascii to native format
-		#
-		fmt=`echo $INITIAL_SIGMA | sed 's/.*\.//g'`
-		@ETC_DIR@/scnvrt gsm $INITIAL_SFC_FILE_TYPE \
-			@IJCAP@:@ILONF@:@ILATG@:@ILEVS@ \
-			-1:-1:-1:-1:-1 \
-			$fmt:bin $INITIAL_SIGMA:$INITIAL_SFC \
-			cnvrt_initial_sig:cnvrt_initial_sfc || exit 8
-		#
-		# Find initial date and hour
-		#
-		@ETC_DIR@/date cnvrt_initial_sig >date.$$ || exit 8
-		read HH MM DD yyyy FH <date.$$ ; rm date.$$
-		echo $yyyy $MM $DD $HH $FH
-		#
 		# Change input resolution to model resolution
 		#
-		@RUNSCR_DIR@/chgr cnvrt_initial_sig cnvrt_initial_sfc \
-						sigit sfci $INITIAL_SFC_FILE_TYPE || exit 8
+		@RUNSCR_DIR@/chgr $INITIAL_SIGMA || exit 8
 		#
 		# Convert initial sfc file type to model sfc file type
 		#
@@ -156,9 +143,8 @@ if [ @BARO_TEST@ != 1 ]; then
 		ICE_GRB_T0=`eval echo $ICE_ANL_T0`
 		export SST_GRB_T0 SNO_GRB_T0 SCV_GRB_T0 ICE_GRB_T0
 		export iicegrb0 isstgrb0 isnogrb0 ism2grb
-		@RUNSCR_DIR@/sfc0 gsm sfci sfco $INITIAL_SFC_FILE_TYPE || exit 8
+		@RUNSCR_DIR@/sfc0 gsm $INITIAL_SFC || exit 8
 		#
-		cp sfco  sfci     || exit 8
 		cp sigit sigitdt  || exit 8
 		cp sigit sig.ft$h || exit 8
 		cp sfci  sfc.ft$h || exit 8
@@ -166,14 +152,6 @@ if [ @BARO_TEST@ != 1 ]; then
 		@ETC_DIR@/date sigit >date.$$ || exit 8
 		read HH MM DD yyyy FH <date.$$ ; rm date.$$
 		echo $yyyy $MM $DD $HH $FH
-		#
-		#  pgb of the initial
-		#
-		if [ @DOPOST@ = yes ] ; then
-			@RUNSCR_DIR@/pgb $h $h $INTSIG || exit 8
-		elif [ @CATPGB@ = yes ] ; then
-			@ETC_DIR@/catpgb
-		fi
 	fi
 else
 	h=0
@@ -195,98 +173,63 @@ while [ $h -lt $ENDHOUR ] ; do
 	SCV_GRB=`eval echo $SCV_ANL`
 	ICE_GRB=`eval echo $ICE_ANL`
 	export SST_GRB SNO_GRB SCV_GRB ICE_GRB iicegrb isstgrb isnogrb ism2grb
-	export SWHR_GBL LWHR_GBL
+	export SWHR_GBL LWHR_GBL NENS_STOCH
 	@RUNSCR_DIR@/fcstparm $INCHOUR $ENDHOUR $INTSFCX:$INTOMLX \
-						$INTSIG:$INTSFC:$INTFLX:$INTRESTART || exit 8
+						$INTSIG:$INTSFC:$INTFLX:$INTNCO:$INTRESTART || exit 8
 	#
 	# Execute forecast
 	#
-	if [ "$BATCHQUE" = qsub ]; then
-		fcstid=`$BATCHQUE @RUNSCR_DIR@/fcst @BATCHsuffix@`
+	if [ "@BATCHQUE@" == "qsub" ]; then
+#        @BATCHQUE@ -W block=true @RUNSCR_DIR@/fcst || exit 8
+        fcstid=`@BATCHQUE@ @RUNSCR_DIR@/fcst`
 		log_name="fcst.e`echo $fcstid | cut -d'.' -f1`"
-	elif [ "$BATCHQUE" = llsubmit ]; then
-		fcstid=`$BATCHQUE @RUNSCR_DIR@/fcst @BATCHsuffix@`
-		log_name="fcst.e`echo $fcstid | cut -d'.' -f2`"
-	elif [ "$BATCHQUE" = bsub ]; then
-		fcstid0=`$BATCHQUE < @RUNSCR_DIR@/fcst @BATCHsuffix@`
-		fcstid="`echo $fcstid0  | cut -d'<' -f2 | cut -d'>' -f1`"
-		log_name="fcst.e`echo $fcstid`"
 	else
-		fcstid=`$BATCHQUE @RUNSCR_DIR@/fcst @BATCHsuffix@`
+		fcstid=`@BATCHQUE@ @RUNSCR_DIR@/fcst @BATCHsuffix@`
 	fi
 	#
 	# Postprocess (pgb, fgb)
 	#
-	if [ @BARO_TEST@ != 1 ]; then
-		if [ @DOPOST@ = yes ] ; then
-			phs=0
-			phe=$hx
-			phinc=$INTSIG
-			fhs=0
-			fhe=$hx
-			fhinc=$INTFLX
-			export phs phe phinc fhs fhe fhinc
-			if [ "$BATCHQUE" != "" ]; then
-				if [ "$BATCHQUE" = llsubmit ]; then
-					@RUNSCR_DIR@/wait_que_job $fcstid $log_name $BATCHstatus || exit 8
-					fcstid=""
-				fi
-				if [ "$BATCHQUE" = bsub ]; then
-					pgbid=`${BATCHQUE} ${BATCHdepend} "done(${fcstid})" \
-                           < @RUNSCR_DIR@/pgb @BATCHsuffix@`
-					fgbid=`${BATCHQUE} ${BATCHdepend} "done(${fcstid})" \
-                           < @RUNSCR_DIR@/fgb @BATCHsuffix@`
-					if [ "$SIG_GRIB" = yes ]; then
-						sgbid=`${BATCHQUE} ${BATCHdepend} "done(${fcstid})" \
-                               < @RUNSCR_DIR@/sgb @BATCHsuffix@`
-					fi
-					pgbid="`echo $pgbid  | cut -d'<' -f2 | cut -d'>' -f1`"
-					fgbid="`echo $fgbid  | cut -d'<' -f2 | cut -d'>' -f1`"
-					sgbid="`echo $sgbid  | cut -d'<' -f2 | cut -d'>' -f1`"
-				else
-	                pgbid=`${BATCHQUE} ${BATCHdepend}${fcstid} @RUNSCR_DIR@/pgb @BATCHsuffix@`
-					fgbid=`${BATCHQUE} ${BATCHdepend}${fcstid} @RUNSCR_DIR@/fgb @BATCHsuffix@`
-					if [ "$SIG_GRIB" = yes ]; then
-						sgbid=`${BATCHQUE} ${BATCHdepend} "done(${fcstid})" \
-                              < @RUNSCR_DIR@/sgb @BATCHsuffix@`
-					fi
-				fi
-			else
-				@RUNSCR_DIR@/pgb $phs $phe $phinc  || exit 8
-				@RUNSCR_DIR@/fgb $fhs $fhe $fhinc  || exit 8
-				if [ "$SIG_GRIB" = yes ]; then
-				@RUNSCR_DIR@/sgb $fhs $fhe $fhinc  || exit 8
-				fi
-			fi
-			#
-			# Wait queue job for fgb and delete flux file
-			#
+	if [ $DO_POST = yes ] ; then
+		phs=$h
+		phe=$hx
+		phinc=$INTSIG
+		fhs=$h
+		fhe=$hx
+		fhinc=$INTFLX
+		if [ $h -gt 0 ]; then
+			phs=`expr $h + $INTSIG`
+			fhs=`expr $h + $INTFLX`
+		fi
+		export phs phe phinc fhs fhe fhinc SIG_GRIB
+		if [ "@BATCHQUE@" == "qsub" ]; then
+#			@BATCHQUE@ -W block=true @RUNSCR_DIR@/post_gmp || exit 8
+			@RUNSCR_DIR@/wait_que_job $fcstid $log_name @BATCHstatus@ || exit 8
+			postid=`@BATCHQUE@ @RUNSCR_DIR@/post_gmp`
+		else
+			@RUNSCR_DIR@/post_gmp $phs $phe $phinc  || exit 8
+		fi
+		#
+		# Wait queue job for post
+		#
+#		if [ "@BATCHQUE@" != "" ]; then
+			@RUNSCR_DIR@/wait_que_job $postid $log_name @BATCHstatus@ || exit 8
+			# delete flux file
 			if [ "$DEL_FLUX" = yes ]; then
-				if [ "$BATCHQUE" != "" ]; then
-					@RUNSCR_DIR@/wait_que_job $fgbid $log_name $BATCHstatus || exit 8
-				fi
 				if [ -s fgb.ft$fhe ]; then
 					@RUNSCR_DIR@/delfile flx 0 $hx $INTFLX || exit 8
 				fi
 			fi
-			#
-			# Wait queue job for pgb
-			#
-			if [ "$BATCHQUE" != "" ]; then
-				@RUNSCR_DIR@/wait_que_job $pgbid $log_name $BATCHstatus || exit 8
-			fi
-			#
-			# find archive files
-			#
-			#cp sig.ft$hx sigit || exit 8
-			#mv sigp.ft$hx sigitdt  || exit 8
-			cp sfc.ft$hx sfci || exit 8
-			if [ "$CPSCLD" = "define" ]; then
-				cp cpscld.ft$hx cpscldi || exit 8
-			fi
-		elif [ @CATPGB@ = yes ] ; then
-			@ETC_DIR@/catpgb
+#		fi
+		#
+		# archive files
+		#
+		if [ "$CPSCLD" = "define" ]; then
+			cp cpscld.ft$hx cpscldi || exit 8
 		fi
+#	elif [ @CATPGB@ = yes ] ; then
+#		@ETC_DIR@/catpgb
+	else
+		@RUNSCR_DIR@/wait_que_job $fcstid $log_name @BATCHstatus@ || exit 8
 	fi
 	#
 	h=$hx
@@ -298,4 +241,16 @@ echo "`date` $0: Completely ended"
 if [ @SYSTEM@ = mac -a @MARCH@ = mpi ] ; then
 	lamclean
 	lamhalt
+fi
+#
+# check
+#
+if [ -s $LRUN/g_000 ]; then
+	VHOUR=`expr $ENDHOUR - $INTSIG`
+	if [ $VHOUR -lt 10 ]; then
+		VHOUR=0$VHOUR
+	fi
+	sigdiff $EXECDIR/sig.ft${VHOUR} $LRUN/g_000/sig.ft${VHOUR}
+	diff $EXECDIR/sig.ft${VHOUR} $LRUN/g_000/sig.ft${VHOUR}
+	diff $EXECDIR/sfc.ft${VHOUR} $LRUN/g_000/sfc.ft${VHOUR}
 fi
diff --git a/expscr/gmp_gfs.in b/expscr/gmp_gfs.in
--- a/expscr/gmp_gfs.in
+++ b/expscr/gmp_gfs.in
@@ -14,8 +14,8 @@ RUNNAME=                # Experimental name
 # Intervals of sfc execution, sigma output, sfc output and flx output
 # Various options for running the model
 #
-SDATE=2012022800        # Starting forecast date
-ENDHOUR=`expr 24 \* 3`  # Length of model integration in hour
+SDATE=${SDATE:=2018071200}  # Starting forecast date
+ENDHOUR=`expr 24 \* 2`  # Length of model integration in hour
 INTPOST=$ENDHOUR        # Time interval to create output files for the first execution
 INCHOUR=$INTPOST        # Forecast hour for the first execution
 INTSFCX=10000000        # Time interval to run surface merging
@@ -23,15 +23,23 @@ INTOMLX=24              # Time interval to run ocean mixed layer model
 INTSIG=6                # Time interval to create sigma output file
 INTSFC=$INTSIG          # Time interval to create surface output file
 INTFLX=$INTSFC          # Time interval to create surface flux output file
+INTNCO=$INTSIG          # Time interavl to create nc output file
 INTSIG2=6               # Time interval to create sigma output file after first execution
 INTSFC2=$INTSIG2        # Time interval to create surface output file after first execution
 INTFLX2=$INTSFC2        # Time interval to create surface flux output file after first execution
-INTRESTART=$ENDHOUR     # Time interval to restart the model
+INTNCO2=$INTSIG2        # Time interavl to create nc output file
 SWHR_GBL=1              # Time interval of shortwave radiation flux (default=6)
-LWHR_GBL=3              # Time interval of longwave  radiation flux
+LWHR_GBL=1              # Time interval of longwave  radiation flux
+INTRESTART=$ENDHOUR     # Time interval to restart the model
 #
-DEL_FLUX=yes            # Option deleting flux file after forecst (yes;no)
+NENS_STOCH=1            # Ensemble number for stochastic perturbation
+#
 FCST_RESTART=yes        # Option indicating whether current forecast is first
+DEL_FLUX=yes            # Option deleting flux file after forecst (yes;no)
+SIG_GRIB=no             # Option gribing at sigma layer after forecst (yes;no)
+POST_SFC=no             # Option post-processing for surface (yes;no or resol.)
+DEL_BINARY=no           # Option deleting binary output after POST_SFC (yes;no)
+#
 SFC_FCST=no             # Option using surface fcst data
 SFC_ASSI_HOUR=12        # Time interval of surface fcst data
 #
@@ -50,39 +58,63 @@ if [ -z $RUNNAME ]; then
 else 
 	EXECDIR=@OUTPUT_DIR@/$RUNNAME
 fi
-export EXECDIR
+export EXECDIR SDATE
 #
 # -------------  do not change below  ------------------------------------------
 #
-mkdir -p $EXECDIR 2>/dev/null
-#
-INPUTDIR=/data6/msk/GFS/GFS/gfs.${SDATE}                # Directory for GFS analysis data 
-SFCDIR=/data3/bbk/obs/${SYYYYMMDD}                      # Directory for sst, sno, ice data
 FHOUR=`expr $SFC_ASSI_HOUR \* -1`
 FDATE=`@ETC_DIR@/validate.s ${SDATE} ${FHOUR}`
 FCSTDIR=@OUTPUT_DIR@/${FDATE}
 #
-INITIAL_SIGMA=${INPUTDIR}/gfs.t${SHOUR}z.sanl
-INITIAL_SFC_ANAL=${INPUTDIR}/gfs.t${SHOUR}z.sfcanl
+mkdir -p $EXECDIR 2>/dev/null
+#
+# namelist
+#
+. @RUNSCR_DIR@/namelist $EXECDIR
+#
+# input data
+#
+#GFS_DIR=/data/DATABASE/ANALYSIS/GFS/gfs_sig/${SYEAR}/${SMON}/gfs.${SDATE}
+GFS_DIR=/home/mskoo/GRIMs/grimsini/gfs/gfs.${SDATE}
+SFC_DIR=${GFS_DIR}
+if [ ${SDATE} -ge 2017071912 ]; then
+	INITIAL_SIG=${GFS_DIR}/gfs.t${SHOUR}z.atmanl.nemsio
+	INITIAL_SFC=${GFS_DIR}/gfs.t${SHOUR}z.sfcanl.nemsio
+else
+	INITIAL_SIG=${GFS_DIR}/gfs.t${SHOUR}z.sanl
+	INITIAL_SFC=${GFS_DIR}/gfs.t${SHOUR}z.sfcanl
+fi
 INITIAL_SFC_FCST=${FCSTDIR}/sfc.ft${SFC_ASSI_HOUR}
-INITIAL_SFC_FILE_TYPE=noa1
 #
 # blank means use guess (in the sfc file).
 #
-SST_ANL_T0=${SFCDIR}/gdas1.t${SHOUR}z.sstgrb.grib2
-ICE_ANL_T0=${SFCDIR}/gdas1.t${SHOUR}z.engicegrb.grib2
-SNO_ANL_T0=${SFCDIR}/gdas1.t${SHOUR}z.snogrb.grib2
-SCV_ANL_T0=
-#
-iicegrb0=1              # 0 : use guess, 1 : use grib file
-isnogrb0=1
-isstgrb0=1
-ism2grb0=0
-#
-SST_ANL=${EXECDIR}/cnvrt_initial_sst
-ICE_ANL=${EXECDIR}/cnvrt_initial_ice
-SNO_ANL=${EXECDIR}/cnvrt_initial_sno
-SCV_ANL=
+if [ ${SYEAR} -ge 2015 ]; then
+    SST_ANL_T0=${SFC_DIR}/rtgssthr_grb_0.5.grib2
+    ICE_ANL_T0=${SFC_DIR}/seaice.t00z.grb.grib2
+    SNO_ANL_T0=
+    SCV_ANL_T0=
+    iicegrb0=1              # 0 : use guess, 1 : use grib file
+    isnogrb0=0
+    isstgrb0=1
+    ism2grb0=0
+    SST_ANL=${EXECDIR}/cnvrt_initial_sst
+    ICE_ANL=${EXECDIR}/cnvrt_initial_ice
+    SNO_ANL=
+    SCV_ANL=
+else
+	SST_ANL_T0=${SFC_DIR}/gdas1.t${SHOUR}z.sstgrb.grib2
+	ICE_ANL_T0=${SFC_DIR}/gdas1.t${SHOUR}z.engicegrb.grib2
+	SNO_ANL_T0=
+	SCV_ANL_T0=
+	iicegrb0=1              # 0 : use guess, 1 : use grib file
+	isnogrb0=0
+	isstgrb0=1
+	ism2grb0=0
+	SST_ANL=${EXECDIR}/cnvrt_initial_sst
+	ICE_ANL=${EXECDIR}/cnvrt_initial_ice
+	SNO_ANL=
+	SCV_ANL=
+fi
 #
 iicegrb=$iicegrb0
 isnogrb=$isnogrb0
@@ -93,10 +125,6 @@ INPUT_RESOLUTION=t@IJCAP@k@ILEVS@
 #
 FCST_NPES=@NPES@
 FCST_NCPUS=@NCPUS@
-#
-# set environmental variables
-#
-. @RUNSCR_DIR@/envset
 #
 # cd to run directory
 #
@@ -119,14 +147,13 @@ if [ @BARO_TEST@ != 1 ]; then
 		# Restart
 		#
 		h=`@ETC_DIR@/fhour sigit`
-		echo fhour in the sigit file = $h
+        if [ "$h" == "" ]; then
+            echo "error in reading forecast hour of sigit."
+            exit 8
+        else
+            echo fhour in the sigit file = $h
+        fi
 	else
-		#
-		# co2
-		#
-		if [ ! -s co2con ] ; then
-			@RUNSCR_DIR@/co2 || exit 8
-		fi
 		#
 		# mountain
 		#
@@ -137,28 +164,6 @@ if [ @BARO_TEST@ != 1 ]; then
 		# Initial start.
 		#
 		h=00
-		#
-		# Conversion from GFS ieee to GRIMs binary format
-		#
-		fmt=`echo $INITIAL_SIGMA | sed 's/.*\.//g'`
-        if [ -s $INITIAL_SIGMA -a \( -s $INITIAL_SFC_ANAL -o -s $INITIAL_SFC_FCST \) ]; then
-            echo 'Conversion from GFS ieee to GRIMs binary format...'
-            if [ "$SFC_FCST" = no ]; then
-                @ETC_DIR@/scnvrt_gfs gsm noa1 \
-                        @IJCAP@:@ILONF@:@ILATG@:@ILEVS@ \
-                        -1:-1:-1:-1:-1 \
-                        ieee:bin $INITIAL_SIGMA:$INITIAL_SFC_ANAL \
-                        cnvrt_initial_sig:cnvrt_initial_sfc || exit 8
-            else
-                @ETC_DIR@/scnvrt_gfs gsm noa1 \
-                        @IJCAP@:@ILONF@:@ILATG@:@ILEVS@ \
-                        -1:-1:-1:-1:-1 \
-                        ieee:bin $INITIAL_SIGMA:dummy \
-                        cnvrt_initial_sig:dummy || exit 8
-            fi
-        else
-            echo 'Initial sigma or surface data is empty.' ; exit 8
-        fi
 		#
 		# Format conversion from grib2 to grib1
 		#
@@ -178,36 +183,9 @@ if [ @BARO_TEST@ != 1 ]; then
 			echo 'SNOW data is empty.' ; exit 8
 		fi
 		#
-		# Find initial date and hour
-		#
-		@ETC_DIR@/date cnvrt_initial_sig >date.$$ || exit 8
-		read HH MM DD YYYY FH <date.$$ ; rm date.$$
-		echo $YYYY $MM $DD $HH $FH
-		#
 		# Change input resolution to model resolution
 		#
-        if [ "$SFC_FCST" = no ]; then
-            @RUNSCR_DIR@/chgr cnvrt_initial_sig cnvrt_initial_sfc \
-                        sigit sfci $INITIAL_SFC_FILE_TYPE || exit 8
-        else
-            @RUNSCR_DIR@/chgr cnvrt_initial_sig dummy \
-                        sigit dummy $INITIAL_SFC_FILE_TYPE || exit 8
-        fi
-        #
-        # Surface field
-        #
-        if [ "$SFC_FCST" = yes ]; then
-                cp $FCSTDIR/sig.ft$SFC_ASSI_HOUR sig_guess  || exit 8
-                cp $INITIAL_SFC_FCST sfc_guess  || exit 8
-                @ETC_DIR@/date sfc_guess >date.$$ || exit 8
-                read BHH BMM BDD BYYYY BFH <date.$$ ; rm date.$$
-                sfc_guess_fcst=`@ETC_DIR@/validate.s $BYYYY$BMM$BDD$BHH $BFH`
-                if [ $SDATE != $sfc_guess_fcst ]; then
-                    echo 'Starting time and fcst time in sfc file are not same.' ; exit 8
-                fi
-                @RUNENV@ @RUNSCR_DIR@/chgdates $YYYY:$MM:$DD:$HH:0 \
-                                sig_guess:sfc_guess dummy:sfci || exit 8
-        fi
+		@RUNSCR_DIR@/chgr $INITIAL_SIG || exit 8
 		#
 		# Convert initial sfc file type to model sfc file type
 		#
@@ -217,9 +195,8 @@ if [ @BARO_TEST@ != 1 ]; then
 		ICE_GRB_T0=`eval echo $ICE_ANL`
 		export SST_GRB_T0 SNO_GRB_T0 SCV_GRB_T0 ICE_GRB_T0
 		export iicegrb0 isstgrb0 isnogrb0 ism2grb
-		@RUNSCR_DIR@/sfc0 gsm sfci sfco $INITIAL_SFC_FILE_TYPE || exit 8
+		@RUNSCR_DIR@/sfc0 gsm $INITIAL_SFC || exit 8
 		#
-		cp sfco  sfci     || exit 8
 		cp sigit sigitdt  || exit 8
 		cp sigit sig.ft$h || exit 8
 		cp sfci  sfc.ft$h || exit 8
@@ -251,6 +228,7 @@ while [ $h -lt $ENDHOUR ] ; do
             INTSIG=$INTSIG2
             INTSFC=$INTSFC2
             INTFLX=$INTFLX2
+            INTNCO=$INTNCO2
         fi
     fi
 	if [ $hx -lt 10 ];then hx=0$hx;fi
@@ -260,92 +238,67 @@ while [ $h -lt $ENDHOUR ] ; do
 	SCV_GRB=`eval echo $SCV_ANL`
 	ICE_GRB=`eval echo $ICE_ANL`
 	export SST_GRB SNO_GRB SCV_GRB ICE_GRB iicegrb isstgrb isnogrb ism2grb
-	export SWHR_GBL LWHR_GBL
+	export SWHR_GBL LWHR_GBL NENS_STOCH
 	@RUNSCR_DIR@/fcstparm $INCHOUR $ENDHOUR $INTSFCX:$INTOMLX \
-						$INTSIG:$INTSFC:$INTFLX:$INTRESTART || exit 8
+						$INTSIG:$INTSFC:$INTFLX:$INTNCO:$INTRESTART || exit 8
 	#
 	# Execute forecast
 	#
-    if [ "$BATCHQUE" = qsub ]; then
-        fcstid=`$BATCHQUE @RUNSCR_DIR@/fcst @BATCHsuffix@`
+    if [ "@BATCHQUE@" == "qsub" ]; then
+#		@BATCHQUE@ -W block=true @RUNSCR_DIR@/fcst || exit 8
+        fcstid=`@BATCHQUE@ @RUNSCR_DIR@/fcst`
         log_name="fcst.e`echo $fcstid | cut -d'.' -f1`"
-    elif [ "$BATCHQUE" = llsubmit ]; then
-        fcstid=`$BATCHQUE @RUNSCR_DIR@/fcst @BATCHsuffix@`
+    elif [ @BATCHQUE@ = llsubmit ]; then
+        fcstid=`@BATCHQUE@ @RUNSCR_DIR@/fcst @BATCHsuffix@`
         log_name="fcst.e`echo $fcstid | cut -d'.' -f2`"
-    elif [ "$BATCHQUE" = bsub ]; then
-        fcstid0=`$BATCHQUE < @RUNSCR_DIR@/fcst @BATCHsuffix@`
+    elif [ @BATCHQUE@ = bsub ]; then
+        fcstid0=`@BATCHQUE@ < @RUNSCR_DIR@/fcst @BATCHsuffix@`
         fcstid="`echo $fcstid0  | cut -d'<' -f2 | cut -d'>' -f1`"
         log_name="fcst.e`echo $fcstid`"
+	else
+		fcstid=`@BATCHQUE@ @RUNSCR_DIR@/fcst @BATCHsuffix@`
     fi
 	#
 	# Postprocess (pgb, fgb)
 	#
 	if [ @BARO_TEST@ != 1 ]; then
 		if [ @DOPOST@ = yes ] ; then
-			phs=0
+			phs=$h
 			phe=$hx
 			phinc=$INTSIG
-			fhs=0
+			fhs=$h
 			fhe=$hx
 			fhinc=$INTFLX
 			if [ $h -gt 0 ]; then
 				phs=`expr $h + $INTSIG`
 				fhs=`expr $h + $INTFLX`
 			fi
-			export phs phe phinc fhs fhe fhinc
-			if [ "$BATCHQUE" != "" ]; then
-				if [ "$BATCHQUE" = llsubmit ]; then
-					@RUNSCR_DIR@/wait_que_job $fcstid $log_name $BATCHstatus || exit 8
-					fcstid=""
-				fi
-                if [ "$BATCHQUE" = bsub ]; then
-                    pgbid=`${BATCHQUE} ${BATCHdepend} "done(${fcstid})" \
-                           < @RUNSCR_DIR@/pgb @BATCHsuffix@`
-                    fgbid=`${BATCHQUE} ${BATCHdepend} "done(${fcstid})" \
-                           < @RUNSCR_DIR@/fgb @BATCHsuffix@`
-                    if [ "$SIG_GRIB" = yes ]; then
-                        sgbid=`${BATCHQUE} ${BATCHdepend} "done(${fcstid})" \
-                               < @RUNSCR_DIR@/sgb @BATCHsuffix@`
-                    fi
-                    pgbid="`echo $pgbid  | cut -d'<' -f2 | cut -d'>' -f1`"
-                    fgbid="`echo $fgbid  | cut -d'<' -f2 | cut -d'>' -f1`"
-                    sgbid="`echo $sgbid  | cut -d'<' -f2 | cut -d'>' -f1`"
-                else
-                    pgbid=`${BATCHQUE} ${BATCHdepend}${fcstid} @RUNSCR_DIR@/pgb @BATCHsuffix@`
-                    fgbid=`${BATCHQUE} ${BATCHdepend}${fcstid} @RUNSCR_DIR@/fgb @BATCHsuffix@`
-                    if [ "$SIG_GRIB" = yes ]; then
-                        sgbid=`${BATCHQUE} ${BATCHdepend} "done(${fcstid})" \
-                              < @RUNSCR_DIR@/sgb @BATCHsuffix@`
-                    fi
-                fi
+			export phs phe phinc fhs fhe fhinc SIG_GRIB POST_SFC DEL_BINARY
+			if [ "@BATCHQUE@" == "qsub" ]; then
+#				@BATCHQUE@ -W block=true @RUNSCR_DIR@/post_gmp || exit 8
+				@RUNSCR_DIR@/wait_que_job $fcstid $log_name @BATCHstatus@ || exit 8
+				postid=`@BATCHQUE@ @RUNSCR_DIR@/post_gmp`
 			else
-				@RUNSCR_DIR@/pgb $phs $phe $phinc  || exit 8
-				@RUNSCR_DIR@/fgb $fhs $fhe $fhinc  || exit 8
+				@RUNSCR_DIR@/post_gmp $phs $phe $phinc  || exit 8
 			fi
 			#
-			# Wait for queue job of fgb and delete flux file
-			#
-			if [ "$DEL_FLUX" = yes ]; then
-				if [ "$BATCHQUE" != "" ]; then
-					@RUNSCR_DIR@/wait_que_job $fgbid $log_name $BATCHstatus || exit 8
-				fi
-				# delete flux file
-				if [ -s fgb.ft$fhe ]; then
-  	 	 			@RUNSCR_DIR@/delfile flx 0 $hx $INTFLX || exit 8
-				fi
-			fi
-			#
-            # Wait for queue job of pgb
+            # Wait queue job for post
             #
-            if [ "$BATCHQUE" != "" ]; then
-                @RUNSCR_DIR@/wait_que_job $pgbid $log_name $BATCHstatus || exit 8
+#			if [ "@BATCHQUE@" != "" ]; then
+                @RUNSCR_DIR@/wait_que_job $postid $log_name @BATCHstatus@ || exit 8
+				# delete flux file
+				if [ "$DEL_FLUX" = yes ]; then
+					if [ -s fgb.ft$fhe ]; then
+  	 	 				@RUNSCR_DIR@/delfile flx 0 $hx $INTFLX || exit 8
+					fi
+				fi
+#			fi
+			#
+			# archive files
+			#
+            if [ "$CPSCLD" = "define" ]; then
+                cp cpscld.ft$hx cpscldi || exit 8
             fi
-			#
-			# find archive files
-			#
-			#cp sig.ft$hx sigit || exit 8
-			#mv sigp.ft$hx sigitdt  || exit 8
-			cp sfc.ft$hx sfci || exit 8
 		elif [ @CATPGB@ = yes ] ; then
 			@ETC_DIR@/catpgb
 		fi
diff --git a/expscr/smp.in b/expscr/smp.in
--- a/expscr/smp.in
+++ b/expscr/smp.in
@@ -10,133 +10,215 @@ set -ax
 #
 #    Program history :
 #
-#    01-19-2004   Young-Hwa Byun       Initial development
-#    08-19-2008   Kyung-Hee Seol       Nudging options, lsm options
-#    03-19-2010   Song-You Hong        Clean up, grims setup
+#    2015-01-19 young-hwa byun  initial development
+#    2008-08-19 kyung-hee seol  nudging options, lsm options
+#    2010-03-19 song-you hong   clean up, grims setup
+#    2015-09-03 myung-seo koo   dimension allocatable
+#    2019-09-19 myung-seo koo   dynamic run not depending configure-run
 #
 #-----------------------------------------------------------------------------
 #
-RUNNAME=s_000
+# select from arms18/arms38/gate19/toga40/trmm37
+#             usgp37/mana45/mc3e42/peca41/iop142/iop242 for dcp
 #
-# -----------------------------------------------------------------------------
+obs_smp=${scase:="usgp37"}
+levs=64   # 0 for default level if sigma coordinate
 #
-host=`hostname | cut -d . -f1`
-if [ $host = global ];then
-	host_head=''
-else
-	host_head='/global'
+if [ $# -eq 1 ]; then
+	obs_smp=$1
+fi
+if [ "$obs_smp" -ne "arms18" -o "$obs_smp" -ne "arms38" -o \
+	 "$obs_smp" -ne "gate19" -o "$obs_smp" -ne "toga40" -o \
+	 "$obs_smp" -ne "trmm37" -o "$obs_smp" -ne "usgp37" -o \
+	 "$obs_smp" -ne "mana45" -o "$obs_smp" -ne "mc3e42" -o \
+	 "$obs_smp" -ne "peca41" -o "$obs_smp" -ne "iop142" -o \
+	 "$obs_smp" -ne "iop242" ]; then
+	echo "obs_smp should be arms18/arms38/gate19/toga40/trmm37/usgp37/mana45/mc3e42/peca41/iop142/iop242"
+	exit 8
 fi
 #
-smp_lsm=@FCST_SFC_FILE_TYPE@
-obs_smp=@SMP_OBS@
-site=@SITE_NAME@
+# site for ceop64
 #
-if [ $obs_smp = toga40 ]; then
-    obs='toga'
-elif [ $obs_smp = arms18 ]; then
-    obs='arm97'
-elif [ $obs_smp = arms38 ]; then
-    obs='arm00'
-elif [ $obs_smp = ceop64 ]; then
-    obs='ceop64'
-fi
-#
-# set environmental variables
-#
-. @RUNSCR_DIR@/envset
+site='KOREAN'
 #
 # Intervals of sigma output, sfc output and flx output
 #
 INTSFCX=24
 INTOMLX=24
-if [ $obs = arm00 -o $obs = arm97 -o $obs = ceop64 ]; then
-	INTSFC=3
-	INTSIG=3
-	INTFLX=3
+if [ $obs_smp = usgp37 -o $obs_smp = mana45 -o $obs_smp = peca41 -o \
+	$obs_smp = iop142 -o $obs_smp = iop242 -o $obs_smp = mc3e42 ] ; then
+INTSFC=1
+INTSIG=1
+INTFLX=1
+INTNCO=1
 else
-	INTSFC=6
-	INTSIG=6
-	INTFLX=6
+INTSFC=3
+INTSIG=3
+INTFLX=3
+INTNCO=3
 fi
-INTRESTART=24
-SWHR_GBL=$INTFLX
-LWHR_GBL=$INTFLX
+SWHR_GBL=1
+LWHR_GBL=1
 export SWHR_GBL LWHR_GBL
 #
-FCST_RESTART=no
+INITIAL_SFC_DIR=@SMPCON_DIR@/ncep_sfc
 #
-if [ $smp_lsm = osu1 ]; then
-	smp_sfc=no
+if [ $obs_smp = usgp37 ]; then
+	SYEAR=2004 # 2004~2015 (125*15)
+	subs=1; sube=125 
+elif [ $obs_smp = mana45 ]; then
+	SYEAR=2014 # 2014/2015
+	subs=1; sube=361
+elif [ $obs_smp = iop142 -o $obs_smp = iop242 ]; then
+	subs=1; sube=36
+elif [ $obs_smp = mc3e42 ]; then
+	subs=1; sube=42
+elif [ $obs_smp = peca41 ]; then
+	subs=1; sube=41
 else
-	smp_sfc=yes
+	subs=1; sube=1
 fi
-#
-INPUT_RESOLUTION=t@IJCAP@k@ILEVS@
-#
-sub=1
-if [ $obs = arm97 ]; then
-	subc=1
-else
-	subc=1
-fi
-#
-while [ $sub -le $subc ]; do
+sub=$subs
+while [ $sub -le $sube ]; do
 	if [ $sub -eq 1 ]; then
 		exp=A
 	fi
-	if [ $obs = toga ]; then
-		yymm=9211
+	if [ $obs_smp = toga40 ]; then
 		SYYYYMMDDHH=1992122000
 		EYYYYMMDDHH=1992122600
-		gr_stime=00Z20Dec1992
-	elif [ $obs = arm00 ]; then
-		yymm=0003
+	elif [ $obs_smp = trmm37 ]; then
+		SYYYYMMDDHH=1999081000
+		EYYYYMMDDHH=1999082000
+	elif [ $obs_smp = gate19 ]; then
+		SYYYYMMDDHH=1974083000
+		EYYYYMMDDHH=1974091903
+	elif [ $obs_smp = arms38 ]; then
 		SYYYYMMDDHH=2000030118
 		EYYYYMMDDHH=2000032209
-		gr_stime=18Z01Mar2000
-	elif [ $obs = arm97 ]; then
-		yymm=9707
+	elif [ $obs_smp = arms18 ]; then
 		if [ $sub = 1 ]; then
 			SYYYYMMDDHH=1997062700
 			EYYYYMMDDHH=1997071800
-			gr_stime=00Z27Jun1997
 			exp=A
 		elif [ $sub = 2 ]; then
 			SYYYYMMDDHH=1997070800
 			EYYYYMMDDHH=1997071300
-			gr_stime=00Z08Jul1997
 			exp=B
 		elif [ $sub = 3 ]; then
 			SYYYYMMDDHH=1997071300
 			EYYYYMMDDHH=1997071800
-			gr_stime=00Z13Jul1997
 			exp=C
 		fi
-	elif [ $obs = ceop64 ]; then
+	elif [ $obs_smp = usgp37 ]; then
+		sname="sgp"
+		IYYYYMMDDHH=${SYEAR}042800
+		fhour=`echo "($sub-1)%125*24;" | bc`
+		SYYYYMMDDHH=`validate.s $IYYYYMMDDHH $fhour`
+		if [ $sub -gt 125 -a $fhour -eq 0 ]; then
+			SYEAR=`echo $SYYYYMMDDHH | cut -c1-4`	
+			SYEAR=`expr $Y4 + 1`
+			SYYYYMMDDHH=${SYEAR}042800
+		fi
+		if [ $sub -eq $sube ]; then
+			EYYYYMMDDHH=`validate.s $SYYYYMMDDHH 120`
+		else
+			EYYYYMMDDHH=`validate.s $SYYYYMMDDHH 123`
+		fi
+		YEAR=`echo $SYYYYMMDDHH | cut -c 1-4`
+		MM=`echo $SYYYYMMDDHH | cut -c 5-6`
+        INITIAL_SFC_DIR=/home/mskoo/GRIMs/grimsini/ra2/sfc/$YEAR/$MM
+        DCP_DIR='/home/mskoo/project/DCP/original_varanal'
+	elif [ $obs_smp = mana45 ]; then
+		sname="goamazon$SYEAR"
+		IYYYYMMDDHH=${SYEAR}010100
+		fhour=`echo "($sub-1)*24;" | bc`
+		SYYYYMMDDHH=`validate.s $IYYYYMMDDHH $fhour`
+		if [ $sub -eq $sube ]; then
+			EYYYYMMDDHH=`validate.s $SYYYYMMDDHH 120`
+		else
+			EYYYYMMDDHH=`validate.s $SYYYYMMDDHH 123`
+		fi
+		YEAR=`echo $SYYYYMMDDHH | cut -c 1-4`
+		MM=`echo $SYYYYMMDDHH | cut -c 5-6`
+        INITIAL_SFC_DIR=/home/mskoo/GRIMs/grimsini/ra2/sfc/$YEAR/$MM
+        DCP_DIR='/home/mskoo/project/DCP/4.1.2'
+	elif [ $obs_smp = mc3e42 ]; then
+		sname="mc3e"
+#		SYYYYMMDDHH=2011042200
+		IYYYYMMDDHH=2011042200
+		fhour=`echo "scale=5;($sub-1)*24;" | bc`
+		SYYYYMMDDHH=`validate.s $IYYYYMMDDHH $fhour`
+		if [ $sub -eq $sube ]; then
+			EYYYYMMDDHH=`validate.s $SYYYYMMDDHH 120`
+		else
+			EYYYYMMDDHH=`validate.s $SYYYYMMDDHH 123`
+		fi
+		YEAR=`echo $SYYYYMMDDHH | cut -c 1-4`
+		MM=`echo $SYYYYMMDDHH | cut -c 5-6`
+        INITIAL_SFC_DIR=/home/mskoo/GRIMs/grimsini/ra2/sfc/$YEAR/$MM
+		DCP_DIR='/home/mskoo/project/DCP/4.2.1'
+	elif [ $obs_smp = peca41 ]; then
+		sname="pecan"
+#		SYYYYMMDDHH=2015060100
+		IYYYYMMDDHH=2015060100
+		fhour=`echo "scale=5;($sub-1)*24;" | bc`
+		SYYYYMMDDHH=`validate.s $IYYYYMMDDHH $fhour`
+		if [ $sub -eq $sube ]; then
+			EYYYYMMDDHH=`validate.s $SYYYYMMDDHH 120`
+		else
+			EYYYYMMDDHH=`validate.s $SYYYYMMDDHH 123`
+		fi
+		YEAR=`echo $SYYYYMMDDHH | cut -c 1-4`
+		MM=`echo $SYYYYMMDDHH | cut -c 5-6`
+        INITIAL_SFC_DIR=/home/mskoo/GRIMs/grimsini/ra2/sfc/$YEAR/$MM
+		DCP_DIR='/home/mskoo/project/DCP/4.2.1'
+	elif [ $obs_smp = iop142 ]; then
+		sname="goamazonIOP1"
+#		SYYYYMMDDHH=2014021500
+		IYYYYMMDDHH=2014021500
+		fhour=`echo "scale=5;($sub-1)*24;" | bc`
+		SYYYYMMDDHH=`validate.s $IYYYYMMDDHH $fhour`
+		if [ $sub -eq $sube ]; then
+			EYYYYMMDDHH=`validate.s $SYYYYMMDDHH 120`
+		else
+			EYYYYMMDDHH=`validate.s $SYYYYMMDDHH 123`
+		fi
+		YEAR=`echo $SYYYYMMDDHH | cut -c 1-4`
+		MM=`echo $SYYYYMMDDHH | cut -c 5-6`
+        INITIAL_SFC_DIR=/home/mskoo/GRIMs/grimsini/ra2/sfc/$YEAR/$MM
+		DCP_DIR='/home/mskoo/project/DCP/4.2.2/arm-iop/0eval-data/xie/scm-forcing/iop_at_mao/GOAMAZON/IOP1_v1.2'
+	elif [ $obs_smp = iop242 ]; then
+		sname="goamazonIOP2"
+#		SYYYYMMDDHH=2014090100
+		IYYYYMMDDHH=2014090100
+		fhour=`echo "scale=5;($sub-1)*24;" | bc`
+		SYYYYMMDDHH=`validate.s $IYYYYMMDDHH $fhour`
+		if [ $sub -eq $sube ]; then
+			EYYYYMMDDHH=`validate.s $SYYYYMMDDHH 120`
+		else
+			EYYYYMMDDHH=`validate.s $SYYYYMMDDHH 123`
+		fi
+		YEAR=`echo $SYYYYMMDDHH | cut -c 1-4`
+		MM=`echo $SYYYYMMDDHH | cut -c 5-6`
+        INITIAL_SFC_DIR=/home/mskoo/GRIMs/grimsini/ra2/sfc/$YEAR/$MM
+		DCP_DIR='/home/mskoo/project/DCP/4.2.2/arm-iop/0eval-data/xie/scm-forcing/iop_at_mao/GOAMAZON/IOP2_v1.2'
+	elif [ $obs_smp = ceop64 ]; then
 		if [ $site = BERMS ]; then
-			yymm=200307
 			SYYYYMMDDHH=2003070500
 			EYYYYMMDDHH=2003080100
-			gr_stime=00Z05Jul2003
-		elif [ $site = TIEBET ]; then
-			yymm=200306
+		elif [ $site = TIBET ]; then
 			SYYYYMMDDHH=2003060200
 			EYYYYMMDDHH=2003062900
-			gr_stime=00Z02Jun2003
 		elif [ $site = KOREAN -o $sub = HIMALAYAS ]; then
-			yymm=200301
 			SYYYYMMDDHH=2003010100
 			EYYYYMMDDHH=2003020200
-			gr_stime=00Z01Jan2003
 		else
-			yymm=200307
 			SYYYYMMDDHH=2003070100
 			EYYYYMMDDHH=2003080100
-			gr_stime=00Z01Jul1997
 		fi
 		exp=A
 	else
-		echo "unknown SMP observation $obs"
+		echo "unknown SMP observation $obs_smp"
 		exit 1
 	fi
 	#
@@ -156,18 +238,28 @@ while [ $sub -le $subc ]; do
 	# If you wish, you may modify EXECDIR to /tmp directory and keep these
 	# scripts on your permanent disk.
 	#
-	EXECDIR=@OUTPUT_DIR@/$RUNNAME/sub$exp
+	if [ $obs_smp = usgp37 -o $obs_smp = mana45 -o \
+	     $obs_smp = mc3e42 -o $obs_smp = peca41 -o \
+		 $obs_smp = iop142 -o $obs_smp = iop242 ]; then
+		EXECDIR=@OUTPUT_DIR@/$sname/$SYYYYMMDDHH
+	else
+		EXECDIR=@OUTPUT_DIR@/$obs_smp/sub$exp
+	fi
 	mkdir -p $EXECDIR 2>/dev/null
+	#
+	# namelist
+	#
+	. @RUNSCR_DIR@/namelist $EXECDIR || exit 8
 	#
 	# -------------  do not change below  -------------------------------------
 	#
-	INITIAL_SIGMA=@SMPCON_DIR@/ncep_sfc/sig.anl.$SYYYYMMDDHH.ieee
-	INITIAL_SFC=@SMPCON_DIR@/ncep_sfc/sfc.anl.$SYYYYMMDDHH.ieee
-	INITIAL_SFC_FILE_TYPE=osu1
-	#
 	#  blank means use guess (in the sfc file).
 	#
+#	SST_ANL_T0=/data/DATABASE/SST/OISST/gisst22.${YYYYS}.daily
 	SST_ANL_T0=@CON_DIR@/gisst22.${YYYYS}.daily
+	if [ ! -s $SST_ANL_T0 ]; then
+	SST_ANL_T0=@CON_DIR@/clim.sst.grib
+	fi
 	ICE_ANL_T0=@CON_DIR@/clim.ice.r2.1979-1998.grib
 	SNO_ANL_T0=@CON_DIR@/clim.snow.r2.1979-1998.grib
 	SCV_ANL_T0=
@@ -175,9 +267,9 @@ while [ $sub -le $subc ]; do
 	isnogrb0=0
 	isstgrb0=1
 	ism2grb0=0
-	SST_ANL=@CON_DIR@/gisst22.$YYYYS.daily
-	ICE_ANL=@CON_DIR@/clim.ice.r2.1979-1998.grib
-	SNO_ANL=@CON_DIR@/clim.snow.r2.1979-1998.grib
+	SST_ANL=$SST_ANL_T0
+	ICE_ANL=$ICE_ANL_T0
+	SNO_ANL=$SNO_ANL_T0
 	SCV_ANL=
 	iicegrb=$iicegrb0
 	isnogrb=$isnogrb0
@@ -197,25 +289,30 @@ while [ $sub -le $subc ]; do
 	#
 	# Initial & BDY conditions
 	#
-	if [ $obs = toga ]; then
-		cp @SMPCON_DIR@/TOGA/basic/toga40.plev $EXECDIR/obs.plev               || exit 8
+	if [ $obs_smp = toga40 ]; then
 		cp @SMPCON_DIR@/TOGA/9211/_dat/basic_flds.ifa_v2.1 $EXECDIR/.	       || exit 8
 		cp @SMPCON_DIR@/TOGA/9211/_dat/deriv_flds.ifa_v2.1 $EXECDIR/.	       || exit 8
 		cp @SMPCON_DIR@/TOGA/9211/_dat/lsf_flds.ifa_v2.1 $EXECDIR/.		       || exit 8
 		cp @SMPCON_DIR@/TOGA/9211/_dat/misc_flds.ifa_v2.1 $EXECDIR/.		   || exit 8
-		cp @SMPCON_DIR@/ncep_sfc/sfc.anl.$YYYYS$MMS$DDS$HHS.ieee $EXECDIR/.	   || exit 8
-	elif [ $obs = arm00 ]; then
-		cp @SMPCON_DIR@/ARM/basic/arm_sgp00.plev $EXECDIR/obs.plev		       || exit 8
+	elif [ $obs_smp = trmm37 ]; then
+		cp @SMPCON_DIR@/TRMM/9907/surface_kwjx.dat $EXECDIR/.			       || exit 8
+		cp @SMPCON_DIR@/TRMM/9907/layer_kwjx.dat $EXECDIR/.					   || exit 8
+	elif [ $obs_smp = arms38 ]; then
 		cp @SMPCON_DIR@/ARM/0003/surface_0003.dat $EXECDIR/.			       || exit 8
 		cp @SMPCON_DIR@/ARM/0003/layer_0003.dat $EXECDIR/.			           || exit 8
-		cp @SMPCON_DIR@/ncep_sfc/sfc.anl.$YYYYS$MMS$DDS$HHS.ieee $EXECDIR/.	   || exit 8
-	elif [ $obs = arm97 ]; then
-		cp @SMPCON_DIR@/ARM/basic/arm_sgp97.plev $EXECDIR/obs.plev		       || exit 8
+	elif [ $obs_smp = arms18 ]; then
 		cp @SMPCON_DIR@/ARM/9707/source/zhang_v2/surface_9707v2.dat $EXECDIR/. || exit 8
 		cp @SMPCON_DIR@/ARM/9707/source/zhang_v2/layer_9707v2.dat $EXECDIR/.   || exit 8
 		cp @SMPCON_DIR@/ARM/9707/drv/jul97_arm_version2/jul97_zhang_advt_timescale_in.dat $EXECDIR/rlx_advtscl.dat	|| exit 8
-		cp @SMPCON_DIR@/ncep_sfc/sfc.anl.$YYYYS$MMS$DDS$HHS.ieee $EXECDIR/.	   || exit 8
-        else
+	elif [ $obs_smp = usgp37 -o $obs_smp = mana45 -o \
+	       $obs_smp = mc3e42 -o $obs_smp = peca41 -o \
+		   $obs_smp = iop142 -o $obs_smp = iop242 ]; then
+cat > $EXECDIR/namelist.smp << EOF
+&smplist
+idir='$DCP_DIR',
+/
+EOF
+	elif [ $obs_smp = ceop64 ]; then
 		cp @SMPCON_DIR@/CEOP/basic/obs.sig $EXECDIR/obs.sig                    || exit 8
 #		cp /disk6/skh/SCM/obs/CEOP/$site/_out/${site}__MOLTS.dat $EXECDIR/molts.dat           || exit 8
 #		cp /disk6/skh/SCM/obs/CEOP/$site/_out/${site}_${yymm}_sfc.dat $EXECDIR/sfc.dat        || exit 8
@@ -225,13 +322,18 @@ while [ $sub -le $subc ]; do
 #		if [ $site != KOREAN -o $site != HIMALAYAS -o $site != THAILAND ]; then
 #			cp /disk6/skh/SCM/obs/CEOP/$site/_out/${site}_${yymm}_flx.dat $EXECDIR/flx.dat     || exit 8
 #		fi
-		cp @SMPCON_DIR@/ncep_sfc/sfc.anl.$YYYYS$MMS$DDS$HHS.ieee $EXECDIR/.	   || exit 8
 	fi
+	INITIAL_SFC=$INITIAL_SFC_DIR/sfc.anl.$YYYYS$MMS$DDS$HHS.ieee
+	if [ ! -s $INITIAL_SFC ]; then
+		INITIAL_SFC=/data/DATABASE/ANALYSIS/GFS/gfs_sig/$YYYYS/$MMS/gfs.$YYYYS$MMS$DDS$HHS/gfs.t00z.sfcanl
+	fi
+	ln -sf $INITIAL_SFC $EXECDIR/cnvrt_initial_sfc   || exit 8
+#
 	rm -f ERROR.out 2>/dev/null
 	#
 	# Forecast section
 	#
-	if [ -s sigit -a -s sigitdt -a -s sfci -a "$FCST_RESTART" = yes ];then
+	if [ -s sigit -a -s sigitdt -a -s sfci ];then
 		#
 		#  Restart
 		#
@@ -246,12 +348,6 @@ while [ $sub -le $subc ]; do
 		rm out
 	else
 		#
-		# co2
-		#
-		if [ ! -s co2con ] ; then
-			@RUNSCR_DIR@/co2 || exit 8
-		fi
-		#
 		# mountain
 		# 
 		if [ ! -s slmsk  -o ! -s oroggd -o ! -s mtnvar ] ; then
@@ -262,59 +358,28 @@ while [ $sub -le $subc ]; do
 		#
 		h=00
 		#
-		@RUNSCR_DIR@/presmp $YYYYS$MMS$DDS$HHS $YYYYE$MME$DDE$HHE \
-						model_initial_sig model_initial_sfc || exit 8
-		#
-		#  convert to 4-digit year if not
-		#
-		century=`expr \( \( $YYYYS - 1 \) / 100 \) + 1`
-		@RUNSCR_DIR@/cnv4dig model_initial_sig model_initial_sfc \
-				sigit smpsfci $INITIAL_SFC_FILE_TYPE $century || exit 8
-		if [ $smp_sfc = no ]; then 
-			cp smpsfci sfci
-		fi
-		#
-		# Run sfc process 
-		#
-		if [ $smp_sfc = yes ]; then 
-			#
-			# Conversion from ascii to native format
-			#
-			fmt=`echo $INITIAL_SIGMA | sed 's/.*\.//g'`
-			@ETC_DIR@/scnvrt gsm $INITIAL_SFC_FILE_TYPE \
-								62:192:94:28            \
-								-1:-1:-1:-1:-1          \
-								$fmt:bin $INITIAL_SIGMA:$INITIAL_SFC \
-								cnvrt_initial_sig:cnvrt_initial_sfc || exit 8
-			#
-			# Change input resolution to model resolution
-			#
-			@RUNSCR_DIR@/chgr dummy cnvrt_initial_sfc \
-							sigit sfci $INITIAL_SFC_FILE_TYPE || exit 8
-			#
-			#  convert initial sfc file type to model sfc file type
-			#
-			SST_GRB_T0=`eval echo $SST_ANL_T0`
-			SNO_GRB_T0=`eval echo $SNO_ANL_T0`
-			SCV_GRB_T0=`eval echo $SCV_ANL_T0`
-			ICE_GRB_T0=`eval echo $ICE_ANL_T0`
-			export SST_GRB_T0 SNO_GRB_T0 SCV_GRB_T0 ICE_GRB_T0
-			export iicegrb0 isstgrb0 isnogrb0 ism2grb
-			@RUNSCR_DIR@/sfc0 gsm sfci sfco $INITIAL_SFC_FILE_TYPE || exit 8
-			cp sfco sfci
-		fi
-		#
-		cp sigit sigitdt
-		if [ $? -ne 0 ] ; then
-			echo "`date` $0: cp sigit sigitdt failed" >>ERROR.out 
-			exit 8
-		fi
+		# Run presmp process for sigit
+		#  
+		@RUNSCR_DIR@/presmp $YYYYS$MMS$DDS$HHS $YYYYE$MME$DDE$HHE|| exit 8
+		# 
 		cp sigit sig.ft$h
+		cp sigit sigitdt
 		if [ $? -ne 0 ] ; then
 			echo "`date` $0: cp sigit sig.ft$h failed" >>ERROR.out
 			exit 8
 		fi
-		cp sfci  sfc.ft$h
+		#
+		# Run sfc process 
+		#
+		SST_GRB_T0=`eval echo $SST_ANL_T0`
+		SNO_GRB_T0=`eval echo $SNO_ANL_T0`
+		SCV_GRB_T0=`eval echo $SCV_ANL_T0`
+		ICE_GRB_T0=`eval echo $ICE_ANL_T0`
+		export SST_GRB_T0 SNO_GRB_T0 SCV_GRB_T0 ICE_GRB_T0
+		export iicegrb0 isstgrb0 isnogrb0 ism2grb
+		@RUNSCR_DIR@/sfc0 gsm cnvrt_initial_sfc  || exit 8
+		# 
+		cp sfci sfc.ft$h
 		if [ $? -ne 0 ] ; then
 			echo "`date` $0: cp sfci sfc.ft$h failed" >>ERROR.out
 			exit 8
@@ -326,7 +391,7 @@ while [ $sub -le $subc ]; do
 	fi
 	#
 	@RUNSCR_DIR@/fcstparm $INCHOUR $ENDHOUR $INTSFCX:$INTOMLX \
-			$INTSIG:$INTSFC:$INTFLX:$INTRESTART || exit 8
+			$INTSIG:$INTSFC:$INTFLX:$INTNCO:$INTRESTART || exit 8
 	#
 	endhour=$ENDHOUR
 	inchour=$INCHOUR
@@ -384,7 +449,7 @@ while [ $sub -le $subc ]; do
 		#	echo "`date` $0: mv sigp.ft$hx sigitdt failed" >>ERROR.out
 		#	exit 8
 		#fi
-		cp sfc.ft$hx sfci
+		#cp sfc.ft$hx sfci
 		if [ $? -ne 0 ] ; then
 			echo "`date` $0: cp sfc.ft$hx sfci failed" >>ERROR.out
 			exit 8
@@ -392,6 +457,7 @@ while [ $sub -le $subc ]; do
 		#
 		#  rename fgb   pgb  dg3cld
 		#
+        if [ "$h" == "000" ]; then h = 00 ; fi
 		YYYY=$YYYYS
 		MM=$MMS
 		DD=$DDS
@@ -400,7 +466,7 @@ while [ $sub -le $subc ]; do
 		hr_end=$hx
 		hr_stp=$hr_str
 		while [ $hr_stp -le $hr_end ] ; do
-			fdate=`@ETC_DIR@/maketim $YYYY$MM$DD$HH -h $hr_stp`
+			fdate=`@ETC_DIR@/validate.s $YYYY$MM$DD$HH $hr_stp`
 			if [ $hr_stp -ne 00 -a $hr_stp -lt 10 ] ; then
 				hr_stp=0$hr_stp
 			fi
@@ -413,7 +479,7 @@ while [ $sub -le $subc ]; do
 		hr_end=$hx
 		hr_stp=$hr_str
 		while [ $hr_stp -le $hr_end ] ; do
-			fdate=`@ETC_DIR@/maketim $YYYY$MM$DD$HH -h $hr_stp`
+			fdate=`@ETC_DIR@/validate.s $YYYY$MM$DD$HH $hr_stp`
 			if [ $hr_stp -ne 00 -a $hr_stp -lt 10 ] ; then
 				hr_stp=0$hr_stp
 			fi
@@ -437,9 +503,16 @@ while [ $sub -le $subc ]; do
 		#
 		h=$hx
 	done
-	if [ -f @POST_DIR@/shell/make_ctl_$obs.$smp_lsm.sh ]; then
-		@POST_DIR@/shell/make_ctl_$obs.$smp_lsm.sh $EXECDIR $gr_stime $INTSIG $ENDHOUR
-	fi
+	#
+	# make control file for GrADs
+	#
+	@RUNSCR_DIR@/makectl pgb
+	@RUNSCR_DIR@/makectl fgb
+	@RUNSCR_DIR@/makectl dg3gb
+	@RUNSCR_DIR@/makectl dcp
+	@RUNSCR_DIR@/makectl cpsgb
+	@RUNSCR_DIR@/makectl cpscld
+	#	
 	if [ -d @POST_DIR@/psmp ]; then
 		for file in `/bin/ls @POST_DIR@/psmp/*.in | sed 's/\.in$//g'`; do
 			sed "s%@EXEC_DIR@%$EXECDIR%g;s%@RUN_DIR@%@RUNS_DIR@%g" $file.in > $file
